config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'quizzes', to: 'quizzes#index'
  post 'start_quiz', to: 'quizzes#start_quiz'
  get 'show_question', to: 'quizzes#show_question'
  post 'submit_answer', to: 'quizzes#submit_answer'
  get 'show_result', to: 'quizzes#show_result'
  get 'reload', to: 'quizzes#reload'
  get 'redo', to: 'quizzes#redo'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord

    def check_answers(values)
      return_value = true;
      values && values.each do |a|
        if correct_answers[a+'_correct'] == "false"
          return_value = false;
        end 
      end
      if return_value
        return_value = (values.count == answer_number);
      end
      return return_value;
    end
  
    def multiple_answers?
        return answer_number > 1 
    end
  
    def self.find_by_id_or_create(id, data)
      obj = self.find_by_id(id)
      obj || self.create(data)
    end
  
    private
    def answer_number
      count = 0;
      correct_answers.each do |key, value|
        value == "true" && count += 1;
      end
      return count;
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @diffculty_levels = ['easy','medium', 'hard']
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def index 
  end

  def start_quiz
    limit = params[:number]
    category = params[:filter] ? params[:filter][:category] : nil
    difficulty = params[:filter] ? params[:filter][:diffculty] : nil

    # saved in session for reloading
    session[:category] = category
    session[:difficulty] = difficulty
    session[:number] = limit

    # get questions
    response = getQuestions(limit, category, difficulty)

    questions = response.map{|h| Question.find_by_id_or_create(h['id'], h)}
    session[:questions] = questions.map{|q| q.id }
    session[:question_index] = 0;
    session.delete(:answers);

    redirect_to :action => "show_question"
  end

  def show_question
    @question = Question.find(session[:questions][session[:question_index]])
  end

  def submit_answer
    chosed_answers = params[:chosed_answers]
    if (!chosed_answers)
      flash[:notice] = "Plese choose your answer before moving on."
      redirect_to :action => "show_question"
      return
    end

    session[:question_index] += 1;
    index = session[:question_index];
    question_id = params[:question][:id];
    session[:answers] ||= Hash.new;
    session[:answers][question_id] = chosed_answers;

    if index == session[:questions].count 
      check_answers() # check all answers and show result
      redirect_to :action => "show_result"
    else
      redirect_to :action => "show_question"
    end
  end

  def reload
    session[:question_index] = 0;
    session.delete(:answers);
    redirect_to :action => "index"
  end

  def redo
    session[:question_index] = 0;
    session.delete(:answers);
    redirect_to :action => "show_question"
  end

  def show_result
  end

  private
  def request_api(url, limit)
    response = Excon.get(url)
   if response.status == 200
      return JSON.parse(response.body)
   else
    return read_from_local(limit)
   end
  end

  def getQuestions(limit, category, difficulty)
    key = "lw4x9Tf7Qzt5qKUWWUlPb6WmD0O1SnYS9K4EmKEa"
     
    if category      
      questions = []
      category.each { |c|   
        questions += request_api(
        "https://quizapi.io/api/v1/questions?apiKey=#{key}&limit=#{limit}&difficulty=#{difficulty}&category=#{c.downcase}", limit)}
      
      return questions.shuffle!.first(limit.to_i)
    else
      return request_api(
      "https://quizapi.io/api/v1/questions?apiKey=#{key}&limit=#{limit}&difficulty=#{difficulty}&category=#{nil}", limit)
    end
  end

  def check_answers
    session[:answers]
    total_question_number = session[:questions].count
    correct_number = 0
    session[:answers].each do |key, value|
      if Question.find(key).check_answers(value) 
         correct_number += 1
      end
    end
    session[:results] ||= []
    session[:results].count == 5 && session[:results].shift
    session[:results].push([Time.now.strftime("%I:%M%p, %m/%d/%Y"), correct_number, total_question_number])
  end

  def read_from_local(limit)
    data = File.read("quiz.json")
    questions = JSON.parse(data).shuffle!.first(limit.to_i)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/home/index.html.erb
<div class="container-sm  d-flex justify-content-center" style="background-color:whitesmoke;">
    <div>
        <div class="title h1 m-4">
            Welcome to Quiz+ !
        </div>
            
        <%= form_with url: start_quiz_path, method: :post, class: 'm-4' do |form| %>
            <div class="mb-3">
                <%= form.label :number, "Quiz Question Number: (4-8)" %>
                <%= form.number_field :number, in: 4..8, step: 1, style: 'width: 150px', class:'form-control', :required => true, :value => session[:number] %>
            </div>
    
            <div class="mb-3">
                <div class="d-3">Categories</div>
                <%= check_box("filter", "category", {:multiple => true, class: 'btn-check', checked: session[:category] && session[:category].include?('Linux')}, "Linux", nil) %>
                <%= form.label "filter_category_linux", "Linux", class: 'btn btn-outline-secondary' %>
    
                <%= check_box("filter", "category", {:multiple => true, class: 'btn-check', checked: session[:category] && session[:category].include?('DevOps')}, "DevOps", nil) %>
                <%= form.label "filter_category_devops", "DevOps", class: 'btn btn-outline-secondary' %>
    
                <%= check_box("filter", "category", {:multiple => true, class: 'btn-check', checked: session[:category] && session[:category].include?('SQL')}, "SQL", nil) %>
                <%= form.label "filter_category_sql", "SQL", class: 'btn btn-outline-secondary' %>
                
                <%= check_box("filter", "category", {:multiple => true, class: 'btn-check', checked: session[:category] && session[:category].include?('Docker')}, "Docker", nil) %>
                <%= form.label "filter_category_docker", "Docker", class: 'btn btn-outline-secondary' %>

                <%= check_box("filter", "category", {:multiple => true, class: 'btn-check', checked: session[:category] && session[:category].include?('Code')}, "Code", nil) %>
                <%= form.label "filter_category_code", "Code", class: 'btn btn-outline-secondary' %>
            </div>
    
            <div class="mb-3">
                <div class="d-3">Difficulty Level</div>
                <% @diffculty_levels.each do |diffculty| %>
                    <%= form.radio_button "filter[diffculty]", diffculty, class: 'btn-check', checked: (session[:difficulty] == diffculty) %>
                    <%= form.label "filter[diffculty]_#{diffculty}", diffculty, class: 'btn btn-outline-secondary' do %>
                        <%= diffculty.upcase %>
                    <% end %>
                <% end %>
                <div class=" mt-3" style="width: 24rem; background-color: #e2e2e2;">
                    <div class="card-body">
                      <p class="card-text text-muted">Hard questions may have multiple correct answers for each question.</p>
                    </div>
                  </div>
            </div>
            <br/>
            <%= form.submit "Start", class: "btn btn-outline-primary col-6"%>
        <% end %>
    
    </div>
    </div>
    
    

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-6">
        <div>
          <span style="color: red;">
            <i class="far fa-heart"></i>
          </span>
          <span class="m-0">Created by Aili.</span>
        </div>
      </div>

      <div class="col-6 d-flex flex-row-reverse">
        <a class="px-2" href="https://github.com/AiliGong" target="_blank">
          <i class="fab fa-github footer-icon"></i>
        </a>
        <a class="px-2" href="https://www.linkedin.com/in/aili-gong/" target="_blank">
          <i class="fab fa-linkedin footer-icon"></i>   
        </a>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light shadow p-3 mb-5" style="background-color: #98b7e5;">
  <div class="container-fluid">
    <%= link_to "Quiz+", {:controller => :home, :action => :index}, {class:
    "navbar-brand title"}%>

    <div class="nav-item">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <!-- <li class="nav-item active"> -->
          <%= link_to "Home", {:controller => :home, :action => :index}, {class:
            "nav-link"}%>
        <!-- </li> -->
  
      </ul>
        <div class="me-2">
          <i class="far fa-envelope"></i>
        </div>
        <div class="me-1">aili.elly.gong@gmail.com</div>
      </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz+</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">      <title><%= yield(:title) %> | MyShop</title>
    <link rel="preconnect" href="https://fonts.gstatic.com"> 
    <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@600&display=swap" rel="stylesheet">
    <!-- <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet"> -->
    <script src="https://kit.fontawesome.com/9d0a826a8b.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js"
      integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Nunito&display=swap" rel="stylesheet">  
  </head>

  <body>
    <%= render 'layouts/header' %>

    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/quizzes/_question_card.html.erb
<div class="container-md d-flex justify-content-center">
    <div class="p-3 card shadow-lg rounded" style="width: 500px; margin-top:20px">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h5 class="card-title"><%= question.question %></h5>
                </div>    
                    <%= form_with url: submit_answer_path, method: :post, class: '' do |form| %>
                <div class="col-12 mb-4 mt-2" id="questions">
                    <%= hidden_field(:question, :id) %>
                    <% question.answers.each do |key, value| %>
                        <% if value  %>
                        <div class="py-1 w-100 col-12">
                            <%= check_box_tag 'chosed_answers[]' , key , false, class: "pr-5" %> 
                            <%= value %>
                        </div>
                        <% end %>
                        <% end %>
                </div>
                <div class="col-12">

                    <%= form.submit "Submit", class: "btn btn-primary col-12" %>
                </div>
                    <% end %>
            </div>
        </div>
    </div>
</div>

app/views/quizzes/index.html.erb
<h1>Quizzes#index</h1>

app/views/quizzes/show_question.html.erb
<% if flash[:notice] %>
    <div class="alert alert-warning"><%= flash[:notice] %></div>
<% end %>

<%= render 'quizzes/question_card', question: @question %>

app/views/quizzes/show_result.html.erb
<div class="container-md d-flex justify-content-center">
  <div class="p-3 card shadow-lg rounded" style="width: 500px; margin-top:20px">
    <div class="container">
      <div class="row">
        <% if session[:results] %>
        <div class="col-12">
          <p class="h4" style="text-align: center"><%= "This time, you answered " + session[:results][-1][1].to_s + "/" + session[:results][-1][2].to_s + " questions correctly" %></p>
        </div>
        <% session[:results].each_with_index do |value, index| %>
          <% if index + 1 < session[:results].count %> 
            <p class="h5">
              <%= "At " + value[0]  + ", you answered " + value[1].to_s + "/" + value[2].to_s + " questions correctly" %>
            </p>
          <% end %>
        <% end %>
        <%= link_to "Reload", {:controller => :home, :action => :index}, {class:"btn btn-primary m-2"}%>
        <%= link_to "Redo", {:controller => :quizzes, :action => :redo}, {class:"btn btn-primary m-2"}%>

        <% else %>
        <p>
          Please start a quiz to see your resluts!
        </p>
        <% end %>

      </div>
    </div>
  </div>
</div>